#!/bin/bash

# This is based off of Ubuntu's 50_check_unity_support file with the paths
# slightly modified for RPM based distributions.

if [ "x$DESKTOP_SESSION" = "xubuntu" ] && [ ! -f "/tmp/unity_support_test.0" ]; then
    if [ -f "/tmp/unity_support_test.1" ]; then
        DESKTOP_SESSION="ubuntu-2d"
        GDMSESSION="ubuntu-2d"
    else
        /usr/libexec/unity_support_test
        if [ $? -ne 0 ]; then
            DESKTOP_SESSION="ubuntu-2d"
            GDMSESSION="ubuntu-2d"
        fi
    fi
fi

