# Written by: Xiao-Long Chen <chenxiaolong@cxl.epac.to>

# Based off of the Fedora 17 spec file

%define _fedora_rel			22
%define _ubuntu_rel			2ubuntu1
%define _obsolete_ver			7.6-100

%define _ver_bigreqsproto		1.1.2
%define _ver_compositeproto		0.4.1
%define _ver_damageproto		1.2.1
%define _ver_dmxproto			2.3.1
%define _ver_dri2proto			2.8
%define _ver_evieext			1.1.1
%define _ver_fixesproto			5.0
%define _ver_fontsproto			2.1.2
%define _ver_glproto			1.4.16
%define _ver_inputproto			2.2
%define _ver_kbproto			1.0.6
%define _ver_randrproto			1.4.0
%define _ver_recordproto		1.14.2
%define _ver_renderproto		0.11.1
%define _ver_resourceproto		1.2.0
%define _ver_scrnsaverproto		1.2.2
%define _ver_videoproto			2.3.1
%define _ver_xcmiscproto		1.2.2
%define _ver_xextproto			7.2.1
%define _ver_xf86bigfontproto		1.2.0
%define _ver_xf86dgaproto		2.1
%define _ver_xf86driproto		2.1.1
%define _ver_xf86miscproto		0.9.3
%define _ver_xf86vidmodeproto		2.3.1
%define _ver_xineramaproto		1.2.1
%define _ver_xproto			7.0.23
%define _ver_xproxymanagementprotocol	1.0.3

Name:		xorg-x11-proto-ubuntu-devel
Version:	7.6
Release:	1.%{_ubuntu_rel}.fcrel%{_fedora_rel}%{?dist}
Summary:	X.Org X11 Protocol headers

Group:		Development/System
License:	MIT
URL:		http://www.x.org

%define website http://xorg.freedesktop.org/archive/individual/proto

Source0:	%{website}/bigreqsproto-%{_ver_bigreqsproto}.tar.bz2
Source1:        %{website}/compositeproto-%{_ver_compositeproto}.tar.bz2
Source2:        %{website}/damageproto-%{_ver_damageproto}.tar.bz2
Source3:        %{website}/dmxproto-%{_ver_dmxproto}.tar.bz2
Source4:        %{website}/dri2proto-%{_ver_dri2proto}.tar.bz2
Source5:        %{website}/evieext-%{_ver_evieext}.tar.bz2
Source6:        %{website}/fixesproto-%{_ver_fixesproto}.tar.bz2
Source7:        %{website}/fontsproto-%{_ver_fontsproto}.tar.bz2
Source8:        %{website}/glproto-%{_ver_glproto}.tar.bz2
Source9:        %{website}/inputproto-%{_ver_inputproto}.tar.bz2
Source10:       %{website}/kbproto-%{_ver_kbproto}.tar.bz2
Source11:       %{website}/randrproto-%{_ver_randrproto}.tar.bz2
Source12:       %{website}/recordproto-%{_ver_recordproto}.tar.bz2
Source13:       %{website}/renderproto-%{_ver_renderproto}.tar.bz2
Source14:       %{website}/resourceproto-%{_ver_resourceproto}.tar.bz2
Source15:       %{website}/scrnsaverproto-%{_ver_scrnsaverproto}.tar.bz2
Source16:       %{website}/videoproto-%{_ver_videoproto}.tar.bz2
Source17:       %{website}/xcmiscproto-%{_ver_xcmiscproto}.tar.bz2
Source18:       %{website}/xextproto-%{_ver_xextproto}.tar.bz2
Source19:       %{website}/xf86bigfontproto-%{_ver_xf86bigfontproto}.tar.bz2
Source20:       %{website}/xf86dgaproto-%{_ver_xf86dgaproto}.tar.bz2
Source21:       %{website}/xf86driproto-%{_ver_xf86driproto}.tar.bz2
Source22:       %{website}/xf86miscproto-%{_ver_xf86miscproto}.tar.bz2
Source23:       %{website}/xf86vidmodeproto-%{_ver_xf86vidmodeproto}.tar.bz2
Source24:       %{website}/xineramaproto-%{_ver_xineramaproto}.tar.bz2
Source25:       %{website}/xproto-%{_ver_xproto}.tar.bz2
Source26:       %{website}/xproxymanagementprotocol-%{_ver_xproxymanagementprotocol}.tar.bz2

Source98:	make-git-snapshot.sh
Source99:	https://launchpad.net/ubuntu/+archive/primary/+files/x11proto-fixes_%{_ver_fixesproto}-%{_ubuntu_rel}.diff.gz

BuildArch:	noarch

BuildRequires:	autoconf
BuildRequires:	automake

BuildRequires:	xorg-x11-util-macros >= 1.0.2-1

Requires:	libXau-devel
Requires:	mesa-libGL-devel

# Replace official version
Provides:	xorg-x11-proto-devel = %{version}-%{release}
Obsoletes:	xorg-x11-proto-devel < %{_obsolete_ver}

%description
X.Org X11 Protocol headers


%prep
%setup -q -c -a0 -a1 -a2 -a3 -a4 -a5 -a6 -a7 -a8 -a9 -a10 -a11 -a12 -a13 -a14 -a15 -a16 -a17 -a18 -a19 -a20 -a21 -a22 -a23 -a24 -a25 -a26

pushd fixesproto-%{_ver_fixesproto}

# Apply Ubuntu's patches
zcat '%{SOURCE99}' | patch -Np1
for i in $(grep -v '#' debian/patches/series); do
  patch -Np1 -i "debian/patches/${i}"
done

autoreconf -vfi
popd


%build
for i in $(ls -1); do
  pushd ${i}
  [ -x ./configure ] || ./autogen.sh
  # Get pkgconfig files in /usr/share/pkgconfig
  %configure --libdir=%{_datadir} --without-xmlto
  make %{?_smp_mflags}
  mv COPYING COPYING-${i%%-*}
  popd
done


%install
for i in $(ls -1); do
  pushd ${i}
  make install DESTDIR=$RPM_BUILD_ROOT
  install -m444 COPYING-${i%%-*} ${OLDPWD}
  popd
done

# Move documentation to put in correct directory later
mv $RPM_BUILD_ROOT%{_docdir}/*/*.{txt,xml} .
mv $RPM_BUILD_ROOT%{_docdir}/xproxymanagementprotocol/PM_spec .

# Remove HTML documentation generated by xmlto (if installed)
rm -vf $RPM_BUILD_ROOT%{_docdir}/*/*.html


%files
%doc COPYING-*
%doc *.txt
%doc *.xml
%doc PM_spec

%dir %{_includedir}/GL/
%{_includedir}/GL/glxint.h
%{_includedir}/GL/glxmd.h
%{_includedir}/GL/glxproto.h
%{_includedir}/GL/glxtokens.h

%dir %{_includedir}/GL/internal
%{_includedir}/GL/internal/glcore.h

%dir %{_includedir}/X11/
%{_includedir}/X11/DECkeysym.h
%{_includedir}/X11/HPkeysym.h
%{_includedir}/X11/Sunkeysym.h
%{_includedir}/X11/X.h
%{_includedir}/X11/XF86keysym.h
%{_includedir}/X11/XWDFile.h
%{_includedir}/X11/Xalloca.h
%{_includedir}/X11/Xarch.h
%{_includedir}/X11/Xatom.h
%{_includedir}/X11/Xdefs.h
%{_includedir}/X11/Xfuncproto.h
%{_includedir}/X11/Xfuncs.h
%{_includedir}/X11/Xmd.h
%{_includedir}/X11/Xos.h
%{_includedir}/X11/Xos_r.h
%{_includedir}/X11/Xosdefs.h
%{_includedir}/X11/Xpoll.h
%{_includedir}/X11/Xproto.h
%{_includedir}/X11/Xprotostr.h
%{_includedir}/X11/Xthreads.h
%{_includedir}/X11/Xw32defs.h
%{_includedir}/X11/Xwindows.h
%{_includedir}/X11/Xwinsock.h
%{_includedir}/X11/ap_keysym.h
%{_includedir}/X11/keysym.h
%{_includedir}/X11/keysymdef.h

%dir %{_includedir}/X11/PM/
%{_includedir}/X11/PM/PM.h
%{_includedir}/X11/PM/PMproto.h

%dir %{_includedir}/X11/dri/
%{_includedir}/X11/dri/xf86dri.h
%{_includedir}/X11/dri/xf86driproto.h
%{_includedir}/X11/dri/xf86dristr.h

%dir %{_includedir}/X11/extensions/
%{_includedir}/X11/extensions/EVI.h
%{_includedir}/X11/extensions/EVIproto.h
%{_includedir}/X11/extensions/XI.h
%{_includedir}/X11/extensions/XI2.h
%{_includedir}/X11/extensions/XI2proto.h
%{_includedir}/X11/extensions/XIproto.h
%{_includedir}/X11/extensions/XKB.h
%{_includedir}/X11/extensions/XKBgeom.h
%{_includedir}/X11/extensions/XKBproto.h
%{_includedir}/X11/extensions/XKBsrv.h
%{_includedir}/X11/extensions/XKBstr.h
%{_includedir}/X11/extensions/XResproto.h
%{_includedir}/X11/extensions/Xeviestr.h
%{_includedir}/X11/extensions/Xv.h
%{_includedir}/X11/extensions/XvMC.h
%{_includedir}/X11/extensions/XvMCproto.h
%{_includedir}/X11/extensions/Xvproto.h
%{_includedir}/X11/extensions/ag.h
%{_includedir}/X11/extensions/agproto.h
%{_includedir}/X11/extensions/bigreqsproto.h
%{_includedir}/X11/extensions/bigreqstr.h
%{_includedir}/X11/extensions/composite.h
%{_includedir}/X11/extensions/compositeproto.h
%{_includedir}/X11/extensions/cup.h
%{_includedir}/X11/extensions/cupproto.h
%{_includedir}/X11/extensions/damageproto.h
%{_includedir}/X11/extensions/damagewire.h
%{_includedir}/X11/extensions/dbe.h
%{_includedir}/X11/extensions/dbeproto.h
%{_includedir}/X11/extensions/dmx.h
%{_includedir}/X11/extensions/dmxproto.h
%{_includedir}/X11/extensions/dpmsconst.h
%{_includedir}/X11/extensions/dpmsproto.h
%{_includedir}/X11/extensions/dri2proto.h
%{_includedir}/X11/extensions/dri2tokens.h
%{_includedir}/X11/extensions/evieproto.h
%{_includedir}/X11/extensions/ge.h
%{_includedir}/X11/extensions/geproto.h
%{_includedir}/X11/extensions/lbx.h
%{_includedir}/X11/extensions/lbxproto.h
%{_includedir}/X11/extensions/mitmiscconst.h
%{_includedir}/X11/extensions/mitmiscproto.h
%{_includedir}/X11/extensions/multibufconst.h
%{_includedir}/X11/extensions/multibufproto.h
%{_includedir}/X11/extensions/panoramiXproto.h
%{_includedir}/X11/extensions/randr.h
%{_includedir}/X11/extensions/randrproto.h
%{_includedir}/X11/extensions/recordconst.h
%{_includedir}/X11/extensions/recordproto.h
%{_includedir}/X11/extensions/recordstr.h
%{_includedir}/X11/extensions/render.h
%{_includedir}/X11/extensions/renderproto.h
%{_includedir}/X11/extensions/saver.h
%{_includedir}/X11/extensions/saverproto.h
%{_includedir}/X11/extensions/secur.h
%{_includedir}/X11/extensions/securproto.h
%{_includedir}/X11/extensions/shapeconst.h
%{_includedir}/X11/extensions/shapeproto.h
%{_includedir}/X11/extensions/shapestr.h
%{_includedir}/X11/extensions/shm.h
%{_includedir}/X11/extensions/shmproto.h
%{_includedir}/X11/extensions/shmstr.h
%{_includedir}/X11/extensions/syncconst.h
%{_includedir}/X11/extensions/syncproto.h
%{_includedir}/X11/extensions/syncstr.h
%{_includedir}/X11/extensions/vldXvMC.h
%{_includedir}/X11/extensions/xcmiscproto.h
%{_includedir}/X11/extensions/xcmiscstr.h
%{_includedir}/X11/extensions/xf86bigfont.h
%{_includedir}/X11/extensions/xf86bigfproto.h
%{_includedir}/X11/extensions/xf86bigfstr.h
%{_includedir}/X11/extensions/xf86dga.h
%{_includedir}/X11/extensions/xf86dga1const.h
%{_includedir}/X11/extensions/xf86dga1proto.h
%{_includedir}/X11/extensions/xf86dga1str.h
%{_includedir}/X11/extensions/xf86dgaconst.h
%{_includedir}/X11/extensions/xf86dgaproto.h
%{_includedir}/X11/extensions/xf86dgastr.h
%{_includedir}/X11/extensions/xf86misc.h
%{_includedir}/X11/extensions/xf86mscstr.h
%{_includedir}/X11/extensions/xf86vm.h
%{_includedir}/X11/extensions/xf86vmproto.h
%{_includedir}/X11/extensions/xf86vmstr.h
%{_includedir}/X11/extensions/xfixesproto.h
%{_includedir}/X11/extensions/xfixeswire.h
%{_includedir}/X11/extensions/xtestconst.h
%{_includedir}/X11/extensions/xtestext1const.h
%{_includedir}/X11/extensions/xtestext1proto.h
%{_includedir}/X11/extensions/xtestproto.h

%dir %{_includedir}/X11/fonts/
%{_includedir}/X11/fonts/FS.h
%{_includedir}/X11/fonts/FSproto.h
%{_includedir}/X11/fonts/font.h
%{_includedir}/X11/fonts/fontproto.h
%{_includedir}/X11/fonts/fontstruct.h
%{_includedir}/X11/fonts/fsmasks.h

%{_datadir}/pkgconfig/bigreqsproto.pc
%{_datadir}/pkgconfig/compositeproto.pc
%{_datadir}/pkgconfig/damageproto.pc
%{_datadir}/pkgconfig/dmxproto.pc
%{_datadir}/pkgconfig/dri2proto.pc
%{_datadir}/pkgconfig/evieproto.pc
%{_datadir}/pkgconfig/fixesproto.pc
%{_datadir}/pkgconfig/fontsproto.pc
%{_datadir}/pkgconfig/glproto.pc
%{_datadir}/pkgconfig/inputproto.pc
%{_datadir}/pkgconfig/kbproto.pc
%{_datadir}/pkgconfig/randrproto.pc
%{_datadir}/pkgconfig/recordproto.pc
%{_datadir}/pkgconfig/renderproto.pc
%{_datadir}/pkgconfig/resourceproto.pc
%{_datadir}/pkgconfig/scrnsaverproto.pc
%{_datadir}/pkgconfig/videoproto.pc
%{_datadir}/pkgconfig/xcmiscproto.pc
%{_datadir}/pkgconfig/xextproto.pc
%{_datadir}/pkgconfig/xf86bigfontproto.pc
%{_datadir}/pkgconfig/xf86dgaproto.pc
%{_datadir}/pkgconfig/xf86driproto.pc
%{_datadir}/pkgconfig/xf86miscproto.pc
%{_datadir}/pkgconfig/xf86vidmodeproto.pc
%{_datadir}/pkgconfig/xineramaproto.pc
%{_datadir}/pkgconfig/xproto.pc
%{_datadir}/pkgconfig/xproxymngproto.pc


%changelog
* Wed Aug 22 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 7.6-2.2ubuntu1.fcrel22
- Fix missing bigreqsproto
- bigreqsproto-1.1.2
- compositeproto-0.4.2
- damageproto-1.2.1
- fontsproto-2.1.2
- inputproto-2.2
- kbproto-1.0.6
- recordproto-1.14.2
- xcmiscproto-1.2.2
- xextproto-7.2.1

* Wed Aug 22 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 7.6-1.2ubuntu1.fcrel22
- Fedora release 22
- glproto 1.4.16
- dri2proto 2.8
- randrproto 1.4.0

* Wed Jul 11 2012 Xiao-Long Chen <chenxiaolong@cxl.epac.to> - 7.6-1.2ubuntu1.fcrel21
- Initial release
- Ubuntu release 2ubuntu1 (patches fixesproto 5.0)
- Based on Fedora release 21
